// Code generated by protoc-gen-gogo.
// source: agent.proto
// DO NOT EDIT!

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	agent.proto
	oci.proto

It has these top-level messages:
	CreateContainerRequest
	StartContainerRequest
	SignalContainerRequest
	NewProcessResponse
	ExecProcessRequest
	SignalProcessRequest
	WaitProcessRequest
	WaitProcessResponse
	WriteStreamRequest
	WriteStreamResponse
	ReadStreamRequest
	ReadStreamResponse
	CloseStdinRequest
	TtyWinResizeRequest
	CreateSandboxRequest
	DestroySandboxRequest
	IpAddress
	UpdateInterfaceRequest
	AddRouteRequest
	OnlineCPUMemRequest
	Storage
	StringUser
	Route
	Spec
	Process
	Box
	User
	LinuxCapabilities
	POSIXRlimit
	Mount
	Root
	Hooks
	Hook
	Linux
	Windows
	Solaris
	LinuxIDMapping
	LinuxNamespace
	LinuxDevice
	LinuxResources
	LinuxMemory
	LinuxCPU
	LinuxWeightDevice
	LinuxThrottleDevice
	LinuxBlockIO
	LinuxPids
	LinuxDeviceCgroup
	LinuxNetwork
	LinuxHugepageLimit
	LinuxInterfacePriority
	LinuxSeccomp
	LinuxSeccompArg
	LinuxSyscall
	LinuxIntelRdt
*/
package grpc

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf2 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type CreateContainerRequest struct {
	ContainerId string      `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	StringUser  *StringUser `protobuf:"bytes,2,opt,name=string_user,json=stringUser" json:"string_user,omitempty"`
	Storages    []*Storage  `protobuf:"bytes,3,rep,name=storages" json:"storages,omitempty"`
	OCI         *Spec       `protobuf:"bytes,4,opt,name=OCI" json:"OCI,omitempty"`
}

func (m *CreateContainerRequest) Reset()                    { *m = CreateContainerRequest{} }
func (m *CreateContainerRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateContainerRequest) ProtoMessage()               {}
func (*CreateContainerRequest) Descriptor() ([]byte, []int) { return fileDescriptorAgent, []int{0} }

func (m *CreateContainerRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *CreateContainerRequest) GetStringUser() *StringUser {
	if m != nil {
		return m.StringUser
	}
	return nil
}

func (m *CreateContainerRequest) GetStorages() []*Storage {
	if m != nil {
		return m.Storages
	}
	return nil
}

func (m *CreateContainerRequest) GetOCI() *Spec {
	if m != nil {
		return m.OCI
	}
	return nil
}

type StartContainerRequest struct {
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
}

func (m *StartContainerRequest) Reset()                    { *m = StartContainerRequest{} }
func (m *StartContainerRequest) String() string            { return proto.CompactTextString(m) }
func (*StartContainerRequest) ProtoMessage()               {}
func (*StartContainerRequest) Descriptor() ([]byte, []int) { return fileDescriptorAgent, []int{1} }

func (m *StartContainerRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type SignalContainerRequest struct {
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Signal      uint32 `protobuf:"varint,2,opt,name=signal,proto3" json:"signal,omitempty"`
	// When all is set to true, the signal will be
	// sent to all processes inside the container.
	All bool `protobuf:"varint,3,opt,name=all,proto3" json:"all,omitempty"`
}

func (m *SignalContainerRequest) Reset()                    { *m = SignalContainerRequest{} }
func (m *SignalContainerRequest) String() string            { return proto.CompactTextString(m) }
func (*SignalContainerRequest) ProtoMessage()               {}
func (*SignalContainerRequest) Descriptor() ([]byte, []int) { return fileDescriptorAgent, []int{2} }

func (m *SignalContainerRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *SignalContainerRequest) GetSignal() uint32 {
	if m != nil {
		return m.Signal
	}
	return 0
}

func (m *SignalContainerRequest) GetAll() bool {
	if m != nil {
		return m.All
	}
	return false
}

// NewProcessResponse contains a Linux PID for a process
// that the agent created and manages.
// Any gRPC request from the host for a PID that is not managed
// by the agent will result in an error. For example, calling
// WaitProcess() with a WaitProcessRequest pid field set to a
// PID that was not created by the agent will return an error
// back to the caller.
type NewProcessResponse struct {
	PID uint32 `protobuf:"varint,1,opt,name=PID,proto3" json:"PID,omitempty"`
}

func (m *NewProcessResponse) Reset()                    { *m = NewProcessResponse{} }
func (m *NewProcessResponse) String() string            { return proto.CompactTextString(m) }
func (*NewProcessResponse) ProtoMessage()               {}
func (*NewProcessResponse) Descriptor() ([]byte, []int) { return fileDescriptorAgent, []int{3} }

func (m *NewProcessResponse) GetPID() uint32 {
	if m != nil {
		return m.PID
	}
	return 0
}

type ExecProcessRequest struct {
	ContainerId string      `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	StringUser  *StringUser `protobuf:"bytes,3,opt,name=string_user,json=stringUser" json:"string_user,omitempty"`
	Process     *Process    `protobuf:"bytes,4,opt,name=process" json:"process,omitempty"`
}

func (m *ExecProcessRequest) Reset()                    { *m = ExecProcessRequest{} }
func (m *ExecProcessRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecProcessRequest) ProtoMessage()               {}
func (*ExecProcessRequest) Descriptor() ([]byte, []int) { return fileDescriptorAgent, []int{4} }

func (m *ExecProcessRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *ExecProcessRequest) GetStringUser() *StringUser {
	if m != nil {
		return m.StringUser
	}
	return nil
}

func (m *ExecProcessRequest) GetProcess() *Process {
	if m != nil {
		return m.Process
	}
	return nil
}

type SignalProcessRequest struct {
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	PID         uint32 `protobuf:"varint,2,opt,name=PID,proto3" json:"PID,omitempty"`
	Signal      uint32 `protobuf:"varint,3,opt,name=signal,proto3" json:"signal,omitempty"`
}

func (m *SignalProcessRequest) Reset()                    { *m = SignalProcessRequest{} }
func (m *SignalProcessRequest) String() string            { return proto.CompactTextString(m) }
func (*SignalProcessRequest) ProtoMessage()               {}
func (*SignalProcessRequest) Descriptor() ([]byte, []int) { return fileDescriptorAgent, []int{5} }

func (m *SignalProcessRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *SignalProcessRequest) GetPID() uint32 {
	if m != nil {
		return m.PID
	}
	return 0
}

func (m *SignalProcessRequest) GetSignal() uint32 {
	if m != nil {
		return m.Signal
	}
	return 0
}

type WaitProcessRequest struct {
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	PID         uint32 `protobuf:"varint,2,opt,name=PID,proto3" json:"PID,omitempty"`
}

func (m *WaitProcessRequest) Reset()                    { *m = WaitProcessRequest{} }
func (m *WaitProcessRequest) String() string            { return proto.CompactTextString(m) }
func (*WaitProcessRequest) ProtoMessage()               {}
func (*WaitProcessRequest) Descriptor() ([]byte, []int) { return fileDescriptorAgent, []int{6} }

func (m *WaitProcessRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *WaitProcessRequest) GetPID() uint32 {
	if m != nil {
		return m.PID
	}
	return 0
}

type WaitProcessResponse struct {
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (m *WaitProcessResponse) Reset()                    { *m = WaitProcessResponse{} }
func (m *WaitProcessResponse) String() string            { return proto.CompactTextString(m) }
func (*WaitProcessResponse) ProtoMessage()               {}
func (*WaitProcessResponse) Descriptor() ([]byte, []int) { return fileDescriptorAgent, []int{7} }

func (m *WaitProcessResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type WriteStreamRequest struct {
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	PID         uint32 `protobuf:"varint,2,opt,name=PID,proto3" json:"PID,omitempty"`
	Data        []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *WriteStreamRequest) Reset()                    { *m = WriteStreamRequest{} }
func (m *WriteStreamRequest) String() string            { return proto.CompactTextString(m) }
func (*WriteStreamRequest) ProtoMessage()               {}
func (*WriteStreamRequest) Descriptor() ([]byte, []int) { return fileDescriptorAgent, []int{8} }

func (m *WriteStreamRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *WriteStreamRequest) GetPID() uint32 {
	if m != nil {
		return m.PID
	}
	return 0
}

func (m *WriteStreamRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type WriteStreamResponse struct {
	Len uint32 `protobuf:"varint,1,opt,name=len,proto3" json:"len,omitempty"`
}

func (m *WriteStreamResponse) Reset()                    { *m = WriteStreamResponse{} }
func (m *WriteStreamResponse) String() string            { return proto.CompactTextString(m) }
func (*WriteStreamResponse) ProtoMessage()               {}
func (*WriteStreamResponse) Descriptor() ([]byte, []int) { return fileDescriptorAgent, []int{9} }

func (m *WriteStreamResponse) GetLen() uint32 {
	if m != nil {
		return m.Len
	}
	return 0
}

type ReadStreamRequest struct {
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	PID         uint32 `protobuf:"varint,2,opt,name=PID,proto3" json:"PID,omitempty"`
	Len         uint32 `protobuf:"varint,3,opt,name=len,proto3" json:"len,omitempty"`
}

func (m *ReadStreamRequest) Reset()                    { *m = ReadStreamRequest{} }
func (m *ReadStreamRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadStreamRequest) ProtoMessage()               {}
func (*ReadStreamRequest) Descriptor() ([]byte, []int) { return fileDescriptorAgent, []int{10} }

func (m *ReadStreamRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *ReadStreamRequest) GetPID() uint32 {
	if m != nil {
		return m.PID
	}
	return 0
}

func (m *ReadStreamRequest) GetLen() uint32 {
	if m != nil {
		return m.Len
	}
	return 0
}

type ReadStreamResponse struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *ReadStreamResponse) Reset()                    { *m = ReadStreamResponse{} }
func (m *ReadStreamResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadStreamResponse) ProtoMessage()               {}
func (*ReadStreamResponse) Descriptor() ([]byte, []int) { return fileDescriptorAgent, []int{11} }

func (m *ReadStreamResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type CloseStdinRequest struct {
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	PID         uint32 `protobuf:"varint,2,opt,name=PID,proto3" json:"PID,omitempty"`
}

func (m *CloseStdinRequest) Reset()                    { *m = CloseStdinRequest{} }
func (m *CloseStdinRequest) String() string            { return proto.CompactTextString(m) }
func (*CloseStdinRequest) ProtoMessage()               {}
func (*CloseStdinRequest) Descriptor() ([]byte, []int) { return fileDescriptorAgent, []int{12} }

func (m *CloseStdinRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *CloseStdinRequest) GetPID() uint32 {
	if m != nil {
		return m.PID
	}
	return 0
}

type TtyWinResizeRequest struct {
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	PID         uint32 `protobuf:"varint,2,opt,name=PID,proto3" json:"PID,omitempty"`
	Row         uint32 `protobuf:"varint,3,opt,name=row,proto3" json:"row,omitempty"`
	Column      uint32 `protobuf:"varint,4,opt,name=column,proto3" json:"column,omitempty"`
}

func (m *TtyWinResizeRequest) Reset()                    { *m = TtyWinResizeRequest{} }
func (m *TtyWinResizeRequest) String() string            { return proto.CompactTextString(m) }
func (*TtyWinResizeRequest) ProtoMessage()               {}
func (*TtyWinResizeRequest) Descriptor() ([]byte, []int) { return fileDescriptorAgent, []int{13} }

func (m *TtyWinResizeRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *TtyWinResizeRequest) GetPID() uint32 {
	if m != nil {
		return m.PID
	}
	return 0
}

func (m *TtyWinResizeRequest) GetRow() uint32 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *TtyWinResizeRequest) GetColumn() uint32 {
	if m != nil {
		return m.Column
	}
	return 0
}

type CreateSandboxRequest struct {
	Hostname     string     `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Dns          []string   `protobuf:"bytes,2,rep,name=dns" json:"dns,omitempty"`
	Storages     []*Storage `protobuf:"bytes,3,rep,name=storages" json:"storages,omitempty"`
	SandboxPidns bool       `protobuf:"varint,4,opt,name=sandbox_pidns,json=sandboxPidns,proto3" json:"sandbox_pidns,omitempty"`
}

func (m *CreateSandboxRequest) Reset()                    { *m = CreateSandboxRequest{} }
func (m *CreateSandboxRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateSandboxRequest) ProtoMessage()               {}
func (*CreateSandboxRequest) Descriptor() ([]byte, []int) { return fileDescriptorAgent, []int{14} }

func (m *CreateSandboxRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *CreateSandboxRequest) GetDns() []string {
	if m != nil {
		return m.Dns
	}
	return nil
}

func (m *CreateSandboxRequest) GetStorages() []*Storage {
	if m != nil {
		return m.Storages
	}
	return nil
}

func (m *CreateSandboxRequest) GetSandboxPidns() bool {
	if m != nil {
		return m.SandboxPidns
	}
	return false
}

type DestroySandboxRequest struct {
}

func (m *DestroySandboxRequest) Reset()                    { *m = DestroySandboxRequest{} }
func (m *DestroySandboxRequest) String() string            { return proto.CompactTextString(m) }
func (*DestroySandboxRequest) ProtoMessage()               {}
func (*DestroySandboxRequest) Descriptor() ([]byte, []int) { return fileDescriptorAgent, []int{15} }

type IpAddress struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Mask    string `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"`
}

func (m *IpAddress) Reset()                    { *m = IpAddress{} }
func (m *IpAddress) String() string            { return proto.CompactTextString(m) }
func (*IpAddress) ProtoMessage()               {}
func (*IpAddress) Descriptor() ([]byte, []int) { return fileDescriptorAgent, []int{16} }

func (m *IpAddress) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *IpAddress) GetMask() string {
	if m != nil {
		return m.Mask
	}
	return ""
}

type UpdateInterfaceRequest struct {
	Type        uint64       `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Device      string       `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	NewName     string       `protobuf:"bytes,3,opt,name=newName,proto3" json:"newName,omitempty"`
	IpAddresses []*IpAddress `protobuf:"bytes,4,rep,name=ipAddresses" json:"ipAddresses,omitempty"`
	Mtu         uint64       `protobuf:"varint,5,opt,name=mtu,proto3" json:"mtu,omitempty"`
}

func (m *UpdateInterfaceRequest) Reset()                    { *m = UpdateInterfaceRequest{} }
func (m *UpdateInterfaceRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateInterfaceRequest) ProtoMessage()               {}
func (*UpdateInterfaceRequest) Descriptor() ([]byte, []int) { return fileDescriptorAgent, []int{17} }

func (m *UpdateInterfaceRequest) GetType() uint64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *UpdateInterfaceRequest) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *UpdateInterfaceRequest) GetNewName() string {
	if m != nil {
		return m.NewName
	}
	return ""
}

func (m *UpdateInterfaceRequest) GetIpAddresses() []*IpAddress {
	if m != nil {
		return m.IpAddresses
	}
	return nil
}

func (m *UpdateInterfaceRequest) GetMtu() uint64 {
	if m != nil {
		return m.Mtu
	}
	return 0
}

type AddRouteRequest struct {
	Routes []*Route `protobuf:"bytes,1,rep,name=routes" json:"routes,omitempty"`
}

func (m *AddRouteRequest) Reset()                    { *m = AddRouteRequest{} }
func (m *AddRouteRequest) String() string            { return proto.CompactTextString(m) }
func (*AddRouteRequest) ProtoMessage()               {}
func (*AddRouteRequest) Descriptor() ([]byte, []int) { return fileDescriptorAgent, []int{18} }

func (m *AddRouteRequest) GetRoutes() []*Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

type OnlineCPUMemRequest struct {
}

func (m *OnlineCPUMemRequest) Reset()                    { *m = OnlineCPUMemRequest{} }
func (m *OnlineCPUMemRequest) String() string            { return proto.CompactTextString(m) }
func (*OnlineCPUMemRequest) ProtoMessage()               {}
func (*OnlineCPUMemRequest) Descriptor() ([]byte, []int) { return fileDescriptorAgent, []int{19} }

type Storage struct {
	Driver     string   `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Source     string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Fstype     string   `protobuf:"bytes,3,opt,name=fstype,proto3" json:"fstype,omitempty"`
	Options    []string `protobuf:"bytes,4,rep,name=options" json:"options,omitempty"`
	MountPoint string   `protobuf:"bytes,5,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
}

func (m *Storage) Reset()                    { *m = Storage{} }
func (m *Storage) String() string            { return proto.CompactTextString(m) }
func (*Storage) ProtoMessage()               {}
func (*Storage) Descriptor() ([]byte, []int) { return fileDescriptorAgent, []int{20} }

func (m *Storage) GetDriver() string {
	if m != nil {
		return m.Driver
	}
	return ""
}

func (m *Storage) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Storage) GetFstype() string {
	if m != nil {
		return m.Fstype
	}
	return ""
}

func (m *Storage) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Storage) GetMountPoint() string {
	if m != nil {
		return m.MountPoint
	}
	return ""
}

type StringUser struct {
	Uid            string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid            string   `protobuf:"bytes,2,opt,name=gid,proto3" json:"gid,omitempty"`
	AdditionalGids []string `protobuf:"bytes,3,rep,name=additionalGids" json:"additionalGids,omitempty"`
}

func (m *StringUser) Reset()                    { *m = StringUser{} }
func (m *StringUser) String() string            { return proto.CompactTextString(m) }
func (*StringUser) ProtoMessage()               {}
func (*StringUser) Descriptor() ([]byte, []int) { return fileDescriptorAgent, []int{21} }

func (m *StringUser) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *StringUser) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *StringUser) GetAdditionalGids() []string {
	if m != nil {
		return m.AdditionalGids
	}
	return nil
}

type Route struct {
	Dest    string `protobuf:"bytes,1,opt,name=dest,proto3" json:"dest,omitempty"`
	Gateway string `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Device  string `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
}

func (m *Route) Reset()                    { *m = Route{} }
func (m *Route) String() string            { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()               {}
func (*Route) Descriptor() ([]byte, []int) { return fileDescriptorAgent, []int{22} }

func (m *Route) GetDest() string {
	if m != nil {
		return m.Dest
	}
	return ""
}

func (m *Route) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

func (m *Route) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateContainerRequest)(nil), "grpc.CreateContainerRequest")
	proto.RegisterType((*StartContainerRequest)(nil), "grpc.StartContainerRequest")
	proto.RegisterType((*SignalContainerRequest)(nil), "grpc.SignalContainerRequest")
	proto.RegisterType((*NewProcessResponse)(nil), "grpc.NewProcessResponse")
	proto.RegisterType((*ExecProcessRequest)(nil), "grpc.ExecProcessRequest")
	proto.RegisterType((*SignalProcessRequest)(nil), "grpc.SignalProcessRequest")
	proto.RegisterType((*WaitProcessRequest)(nil), "grpc.WaitProcessRequest")
	proto.RegisterType((*WaitProcessResponse)(nil), "grpc.WaitProcessResponse")
	proto.RegisterType((*WriteStreamRequest)(nil), "grpc.WriteStreamRequest")
	proto.RegisterType((*WriteStreamResponse)(nil), "grpc.WriteStreamResponse")
	proto.RegisterType((*ReadStreamRequest)(nil), "grpc.ReadStreamRequest")
	proto.RegisterType((*ReadStreamResponse)(nil), "grpc.ReadStreamResponse")
	proto.RegisterType((*CloseStdinRequest)(nil), "grpc.CloseStdinRequest")
	proto.RegisterType((*TtyWinResizeRequest)(nil), "grpc.TtyWinResizeRequest")
	proto.RegisterType((*CreateSandboxRequest)(nil), "grpc.CreateSandboxRequest")
	proto.RegisterType((*DestroySandboxRequest)(nil), "grpc.DestroySandboxRequest")
	proto.RegisterType((*IpAddress)(nil), "grpc.IpAddress")
	proto.RegisterType((*UpdateInterfaceRequest)(nil), "grpc.UpdateInterfaceRequest")
	proto.RegisterType((*AddRouteRequest)(nil), "grpc.AddRouteRequest")
	proto.RegisterType((*OnlineCPUMemRequest)(nil), "grpc.OnlineCPUMemRequest")
	proto.RegisterType((*Storage)(nil), "grpc.Storage")
	proto.RegisterType((*StringUser)(nil), "grpc.StringUser")
	proto.RegisterType((*Route)(nil), "grpc.Route")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for AgentService service

type AgentServiceClient interface {
	// execution
	CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc1.CallOption) (*google_protobuf2.Empty, error)
	StartContainer(ctx context.Context, in *StartContainerRequest, opts ...grpc1.CallOption) (*NewProcessResponse, error)
	SignalContainer(ctx context.Context, in *SignalContainerRequest, opts ...grpc1.CallOption) (*google_protobuf2.Empty, error)
	ExecProcess(ctx context.Context, in *ExecProcessRequest, opts ...grpc1.CallOption) (*NewProcessResponse, error)
	SignalProcess(ctx context.Context, in *SignalProcessRequest, opts ...grpc1.CallOption) (*google_protobuf2.Empty, error)
	WaitProcess(ctx context.Context, in *WaitProcessRequest, opts ...grpc1.CallOption) (*WaitProcessResponse, error)
	// stdio
	WriteStdin(ctx context.Context, in *WriteStreamRequest, opts ...grpc1.CallOption) (*WriteStreamResponse, error)
	ReadStdout(ctx context.Context, in *ReadStreamRequest, opts ...grpc1.CallOption) (*ReadStreamResponse, error)
	ReadStderr(ctx context.Context, in *ReadStreamRequest, opts ...grpc1.CallOption) (*ReadStreamResponse, error)
	CloseStdin(ctx context.Context, in *CloseStdinRequest, opts ...grpc1.CallOption) (*google_protobuf2.Empty, error)
	TtyWinResize(ctx context.Context, in *TtyWinResizeRequest, opts ...grpc1.CallOption) (*google_protobuf2.Empty, error)
	// misc (TODO: some rpcs can be replaced by hyperstart-exec)
	CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc1.CallOption) (*google_protobuf2.Empty, error)
	DestroySandbox(ctx context.Context, in *DestroySandboxRequest, opts ...grpc1.CallOption) (*google_protobuf2.Empty, error)
	UpdateInterface(ctx context.Context, in *UpdateInterfaceRequest, opts ...grpc1.CallOption) (*google_protobuf2.Empty, error)
	AddRoute(ctx context.Context, in *AddRouteRequest, opts ...grpc1.CallOption) (*google_protobuf2.Empty, error)
	OnlineCPUMem(ctx context.Context, in *OnlineCPUMemRequest, opts ...grpc1.CallOption) (*google_protobuf2.Empty, error)
}

type agentServiceClient struct {
	cc *grpc1.ClientConn
}

func NewAgentServiceClient(cc *grpc1.ClientConn) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc1.CallOption) (*google_protobuf2.Empty, error) {
	out := new(google_protobuf2.Empty)
	err := grpc1.Invoke(ctx, "/grpc.AgentService/CreateContainer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StartContainer(ctx context.Context, in *StartContainerRequest, opts ...grpc1.CallOption) (*NewProcessResponse, error) {
	out := new(NewProcessResponse)
	err := grpc1.Invoke(ctx, "/grpc.AgentService/StartContainer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SignalContainer(ctx context.Context, in *SignalContainerRequest, opts ...grpc1.CallOption) (*google_protobuf2.Empty, error) {
	out := new(google_protobuf2.Empty)
	err := grpc1.Invoke(ctx, "/grpc.AgentService/SignalContainer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ExecProcess(ctx context.Context, in *ExecProcessRequest, opts ...grpc1.CallOption) (*NewProcessResponse, error) {
	out := new(NewProcessResponse)
	err := grpc1.Invoke(ctx, "/grpc.AgentService/ExecProcess", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SignalProcess(ctx context.Context, in *SignalProcessRequest, opts ...grpc1.CallOption) (*google_protobuf2.Empty, error) {
	out := new(google_protobuf2.Empty)
	err := grpc1.Invoke(ctx, "/grpc.AgentService/SignalProcess", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) WaitProcess(ctx context.Context, in *WaitProcessRequest, opts ...grpc1.CallOption) (*WaitProcessResponse, error) {
	out := new(WaitProcessResponse)
	err := grpc1.Invoke(ctx, "/grpc.AgentService/WaitProcess", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) WriteStdin(ctx context.Context, in *WriteStreamRequest, opts ...grpc1.CallOption) (*WriteStreamResponse, error) {
	out := new(WriteStreamResponse)
	err := grpc1.Invoke(ctx, "/grpc.AgentService/WriteStdin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReadStdout(ctx context.Context, in *ReadStreamRequest, opts ...grpc1.CallOption) (*ReadStreamResponse, error) {
	out := new(ReadStreamResponse)
	err := grpc1.Invoke(ctx, "/grpc.AgentService/ReadStdout", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReadStderr(ctx context.Context, in *ReadStreamRequest, opts ...grpc1.CallOption) (*ReadStreamResponse, error) {
	out := new(ReadStreamResponse)
	err := grpc1.Invoke(ctx, "/grpc.AgentService/ReadStderr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CloseStdin(ctx context.Context, in *CloseStdinRequest, opts ...grpc1.CallOption) (*google_protobuf2.Empty, error) {
	out := new(google_protobuf2.Empty)
	err := grpc1.Invoke(ctx, "/grpc.AgentService/CloseStdin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) TtyWinResize(ctx context.Context, in *TtyWinResizeRequest, opts ...grpc1.CallOption) (*google_protobuf2.Empty, error) {
	out := new(google_protobuf2.Empty)
	err := grpc1.Invoke(ctx, "/grpc.AgentService/TtyWinResize", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc1.CallOption) (*google_protobuf2.Empty, error) {
	out := new(google_protobuf2.Empty)
	err := grpc1.Invoke(ctx, "/grpc.AgentService/CreateSandbox", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DestroySandbox(ctx context.Context, in *DestroySandboxRequest, opts ...grpc1.CallOption) (*google_protobuf2.Empty, error) {
	out := new(google_protobuf2.Empty)
	err := grpc1.Invoke(ctx, "/grpc.AgentService/DestroySandbox", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UpdateInterface(ctx context.Context, in *UpdateInterfaceRequest, opts ...grpc1.CallOption) (*google_protobuf2.Empty, error) {
	out := new(google_protobuf2.Empty)
	err := grpc1.Invoke(ctx, "/grpc.AgentService/UpdateInterface", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) AddRoute(ctx context.Context, in *AddRouteRequest, opts ...grpc1.CallOption) (*google_protobuf2.Empty, error) {
	out := new(google_protobuf2.Empty)
	err := grpc1.Invoke(ctx, "/grpc.AgentService/AddRoute", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) OnlineCPUMem(ctx context.Context, in *OnlineCPUMemRequest, opts ...grpc1.CallOption) (*google_protobuf2.Empty, error) {
	out := new(google_protobuf2.Empty)
	err := grpc1.Invoke(ctx, "/grpc.AgentService/OnlineCPUMem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AgentService service

type AgentServiceServer interface {
	// execution
	CreateContainer(context.Context, *CreateContainerRequest) (*google_protobuf2.Empty, error)
	StartContainer(context.Context, *StartContainerRequest) (*NewProcessResponse, error)
	SignalContainer(context.Context, *SignalContainerRequest) (*google_protobuf2.Empty, error)
	ExecProcess(context.Context, *ExecProcessRequest) (*NewProcessResponse, error)
	SignalProcess(context.Context, *SignalProcessRequest) (*google_protobuf2.Empty, error)
	WaitProcess(context.Context, *WaitProcessRequest) (*WaitProcessResponse, error)
	// stdio
	WriteStdin(context.Context, *WriteStreamRequest) (*WriteStreamResponse, error)
	ReadStdout(context.Context, *ReadStreamRequest) (*ReadStreamResponse, error)
	ReadStderr(context.Context, *ReadStreamRequest) (*ReadStreamResponse, error)
	CloseStdin(context.Context, *CloseStdinRequest) (*google_protobuf2.Empty, error)
	TtyWinResize(context.Context, *TtyWinResizeRequest) (*google_protobuf2.Empty, error)
	// misc (TODO: some rpcs can be replaced by hyperstart-exec)
	CreateSandbox(context.Context, *CreateSandboxRequest) (*google_protobuf2.Empty, error)
	DestroySandbox(context.Context, *DestroySandboxRequest) (*google_protobuf2.Empty, error)
	UpdateInterface(context.Context, *UpdateInterfaceRequest) (*google_protobuf2.Empty, error)
	AddRoute(context.Context, *AddRouteRequest) (*google_protobuf2.Empty, error)
	OnlineCPUMem(context.Context, *OnlineCPUMemRequest) (*google_protobuf2.Empty, error)
}

func RegisterAgentServiceServer(s *grpc1.Server, srv AgentServiceServer) {
	s.RegisterService(&_AgentService_serviceDesc, srv)
}

func _AgentService_CreateContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CreateContainer(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AgentService/CreateContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CreateContainer(ctx, req.(*CreateContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StartContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StartContainer(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AgentService/StartContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StartContainer(ctx, req.(*StartContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SignalContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SignalContainer(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AgentService/SignalContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SignalContainer(ctx, req.(*SignalContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ExecProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ExecProcess(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AgentService/ExecProcess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ExecProcess(ctx, req.(*ExecProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SignalProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SignalProcess(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AgentService/SignalProcess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SignalProcess(ctx, req.(*SignalProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_WaitProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).WaitProcess(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AgentService/WaitProcess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).WaitProcess(ctx, req.(*WaitProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_WriteStdin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).WriteStdin(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AgentService/WriteStdin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).WriteStdin(ctx, req.(*WriteStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReadStdout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReadStdout(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AgentService/ReadStdout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReadStdout(ctx, req.(*ReadStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReadStderr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReadStderr(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AgentService/ReadStderr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReadStderr(ctx, req.(*ReadStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CloseStdin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseStdinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CloseStdin(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AgentService/CloseStdin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CloseStdin(ctx, req.(*CloseStdinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_TtyWinResize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(TtyWinResizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).TtyWinResize(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AgentService/TtyWinResize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).TtyWinResize(ctx, req.(*TtyWinResizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CreateSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CreateSandbox(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AgentService/CreateSandbox",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CreateSandbox(ctx, req.(*CreateSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DestroySandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroySandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DestroySandbox(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AgentService/DestroySandbox",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DestroySandbox(ctx, req.(*DestroySandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UpdateInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UpdateInterface(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AgentService/UpdateInterface",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UpdateInterface(ctx, req.(*UpdateInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_AddRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).AddRoute(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AgentService/AddRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).AddRoute(ctx, req.(*AddRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_OnlineCPUMem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlineCPUMemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).OnlineCPUMem(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AgentService/OnlineCPUMem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).OnlineCPUMem(ctx, req.(*OnlineCPUMemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AgentService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "CreateContainer",
			Handler:    _AgentService_CreateContainer_Handler,
		},
		{
			MethodName: "StartContainer",
			Handler:    _AgentService_StartContainer_Handler,
		},
		{
			MethodName: "SignalContainer",
			Handler:    _AgentService_SignalContainer_Handler,
		},
		{
			MethodName: "ExecProcess",
			Handler:    _AgentService_ExecProcess_Handler,
		},
		{
			MethodName: "SignalProcess",
			Handler:    _AgentService_SignalProcess_Handler,
		},
		{
			MethodName: "WaitProcess",
			Handler:    _AgentService_WaitProcess_Handler,
		},
		{
			MethodName: "WriteStdin",
			Handler:    _AgentService_WriteStdin_Handler,
		},
		{
			MethodName: "ReadStdout",
			Handler:    _AgentService_ReadStdout_Handler,
		},
		{
			MethodName: "ReadStderr",
			Handler:    _AgentService_ReadStderr_Handler,
		},
		{
			MethodName: "CloseStdin",
			Handler:    _AgentService_CloseStdin_Handler,
		},
		{
			MethodName: "TtyWinResize",
			Handler:    _AgentService_TtyWinResize_Handler,
		},
		{
			MethodName: "CreateSandbox",
			Handler:    _AgentService_CreateSandbox_Handler,
		},
		{
			MethodName: "DestroySandbox",
			Handler:    _AgentService_DestroySandbox_Handler,
		},
		{
			MethodName: "UpdateInterface",
			Handler:    _AgentService_UpdateInterface_Handler,
		},
		{
			MethodName: "AddRoute",
			Handler:    _AgentService_AddRoute_Handler,
		},
		{
			MethodName: "OnlineCPUMem",
			Handler:    _AgentService_OnlineCPUMem_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "agent.proto",
}

func init() { proto.RegisterFile("agent.proto", fileDescriptorAgent) }

var fileDescriptorAgent = []byte{
	// 1055 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0x1b, 0x37,
	0x13, 0x85, 0xb2, 0xf2, 0x8f, 0x46, 0x96, 0x9d, 0xd0, 0xb1, 0xa3, 0x4f, 0x09, 0xf0, 0xb9, 0x1b,
	0x20, 0x51, 0x2f, 0xaa, 0xa0, 0x2e, 0x50, 0x20, 0x05, 0x8a, 0xc2, 0x55, 0x0c, 0x57, 0x17, 0x49,
	0x0c, 0xaa, 0x86, 0x8b, 0x02, 0x85, 0x41, 0x6b, 0xc7, 0xea, 0xa2, 0x12, 0xb9, 0x25, 0xb9, 0x71,
	0xdc, 0x67, 0xe8, 0x5d, 0xfb, 0x06, 0x7d, 0x88, 0x3e, 0x46, 0x5f, 0xa9, 0xe0, 0xdf, 0x6a, 0x25,
	0xaf, 0x8c, 0xc6, 0xce, 0xdd, 0xcc, 0x90, 0x3a, 0x73, 0x66, 0x46, 0x9c, 0xb3, 0xd0, 0x64, 0x63,
	0xe4, 0xba, 0x97, 0x49, 0xa1, 0x05, 0xa9, 0x8f, 0x65, 0x36, 0xea, 0x34, 0xc4, 0x28, 0x75, 0x81,
	0xce, 0xe3, 0xb1, 0x10, 0xe3, 0x09, 0xbe, 0xb0, 0xde, 0x79, 0x7e, 0xf1, 0x02, 0xa7, 0x99, 0xbe,
	0x72, 0x87, 0xf1, 0xdf, 0x35, 0xd8, 0xed, 0x4b, 0x64, 0x1a, 0xfb, 0x82, 0x6b, 0x96, 0x72, 0x94,
	0x14, 0x7f, 0xcd, 0x51, 0x69, 0xf2, 0x09, 0x6c, 0x8c, 0x42, 0xec, 0x2c, 0x4d, 0xda, 0xb5, 0xbd,
	0x5a, 0xb7, 0x41, 0x9b, 0x45, 0x6c, 0x90, 0x90, 0xcf, 0xa1, 0xa9, 0xb4, 0x4c, 0xf9, 0xf8, 0x2c,
	0x57, 0x28, 0xdb, 0xf7, 0xf6, 0x6a, 0xdd, 0xe6, 0xfe, 0xfd, 0x9e, 0x61, 0xd0, 0x1b, 0xda, 0x83,
	0x13, 0x85, 0x92, 0x82, 0x2a, 0x6c, 0xf2, 0x29, 0xac, 0x2b, 0x2d, 0x24, 0x1b, 0xa3, 0x6a, 0x47,
	0x7b, 0x51, 0xb7, 0xb9, 0xdf, 0x0a, 0xf7, 0x6d, 0x94, 0x16, 0xc7, 0xe4, 0x09, 0x44, 0x6f, 0xfb,
	0x83, 0x76, 0xdd, 0xa2, 0x82, 0xbf, 0x95, 0xe1, 0x88, 0x9a, 0x70, 0xfc, 0x15, 0xec, 0x0c, 0x35,
	0x93, 0xfa, 0x16, 0xbc, 0x63, 0x84, 0xdd, 0x61, 0x3a, 0xe6, 0x6c, 0x72, 0x9b, 0xa2, 0x77, 0x61,
	0x55, 0xd9, 0x1f, 0xdb, 0x7a, 0x5b, 0xd4, 0x7b, 0xe4, 0x3e, 0x44, 0x6c, 0x32, 0x69, 0x47, 0x7b,
	0xb5, 0xee, 0x3a, 0x35, 0x66, 0xfc, 0x0c, 0xc8, 0x1b, 0xbc, 0x3c, 0x96, 0x62, 0x84, 0x4a, 0x51,
	0x54, 0x99, 0xe0, 0x0a, 0xcd, 0xbd, 0xe3, 0xc1, 0x2b, 0x8b, 0xdc, 0xa2, 0xc6, 0x8c, 0xff, 0xa8,
	0x01, 0x39, 0x7c, 0x8f, 0xa3, 0xe2, 0xe6, 0x6d, 0x07, 0x10, 0xfd, 0x87, 0x01, 0x3c, 0x87, 0xb5,
	0xcc, 0xe5, 0xf1, 0x9d, 0xf5, 0xfd, 0x0f, 0xc9, 0xc3, 0x69, 0x3c, 0x82, 0x87, 0xae, 0x49, 0x1f,
	0x4e, 0xcb, 0x97, 0x78, 0xaf, 0x28, 0xb1, 0xd4, 0xb4, 0xa8, 0xdc, 0xb4, 0x78, 0x00, 0xe4, 0x94,
	0xa5, 0xfa, 0x23, 0xa4, 0x88, 0x3f, 0x83, 0xed, 0x39, 0x28, 0xdf, 0x6e, 0x93, 0x59, 0x33, 0x9d,
	0x2b, 0x8b, 0xb2, 0x42, 0xbd, 0x17, 0xff, 0x04, 0xe4, 0x54, 0xa6, 0x1a, 0x87, 0x5a, 0x22, 0x9b,
	0xde, 0xa9, 0x38, 0x02, 0xf5, 0x84, 0x69, 0x66, 0x4b, 0xdb, 0xa0, 0xd6, 0x8e, 0x9f, 0xc3, 0xf6,
	0x1c, 0xfc, 0x6c, 0xf8, 0x13, 0xe4, 0x61, 0xf8, 0x13, 0xe4, 0xf1, 0x8f, 0xf0, 0x80, 0x22, 0x4b,
	0x3e, 0x02, 0x0d, 0x8f, 0x1d, 0xcd, 0xb0, 0xbb, 0x40, 0xca, 0xd8, 0x9e, 0x43, 0xa0, 0x5b, 0x2b,
	0xd1, 0xfd, 0x0e, 0x1e, 0xf4, 0x27, 0x42, 0xe1, 0x50, 0x27, 0x29, 0xbf, 0xd3, 0x18, 0x34, 0x6c,
	0x7f, 0xaf, 0xaf, 0x4e, 0x0d, 0x8a, 0x4a, 0x7f, 0xc3, 0xbb, 0x56, 0x24, 0xc5, 0x65, 0xa8, 0x48,
	0x8a, 0x4b, 0x33, 0xcd, 0x91, 0x98, 0xe4, 0x53, 0x6e, 0xff, 0xbc, 0x2d, 0xea, 0xbd, 0xf8, 0xcf,
	0x1a, 0x3c, 0x74, 0x7b, 0x6c, 0xc8, 0x78, 0x72, 0x2e, 0xde, 0x87, 0xbc, 0x1d, 0x58, 0xff, 0x59,
	0x28, 0xcd, 0xd9, 0x14, 0x7d, 0xce, 0xc2, 0x37, 0xf0, 0x09, 0x57, 0xed, 0x7b, 0x7b, 0x51, 0xb7,
	0x41, 0x8d, 0xf9, 0x21, 0xdb, 0xe9, 0x29, 0xb4, 0x94, 0x4b, 0x75, 0x96, 0xa5, 0x06, 0xa6, 0x6e,
	0x1f, 0xfe, 0x86, 0x0f, 0x1e, 0x9b, 0x58, 0xfc, 0x08, 0x76, 0x5e, 0xa1, 0xd2, 0x52, 0x5c, 0xcd,
	0xd3, 0x8a, 0x5f, 0x42, 0x63, 0x90, 0x1d, 0x24, 0x89, 0x44, 0xa5, 0x48, 0x1b, 0xd6, 0x98, 0x33,
	0x3d, 0xc5, 0xe0, 0x9a, 0x51, 0x4d, 0x99, 0xfa, 0xc5, 0xf6, 0xa4, 0x41, 0xad, 0x1d, 0xff, 0x55,
	0x83, 0xdd, 0x93, 0x2c, 0x61, 0x1a, 0x07, 0x5c, 0xa3, 0xbc, 0x60, 0xa3, 0xa2, 0xc9, 0x04, 0xea,
	0xfa, 0x2a, 0x73, 0x85, 0xd6, 0xa9, 0xb5, 0x4d, 0xc7, 0x12, 0x7c, 0x97, 0x8e, 0xd0, 0x83, 0x78,
	0xcf, 0x24, 0xe5, 0x78, 0xf9, 0xc6, 0xf4, 0x25, 0x72, 0x49, 0xbd, 0x6b, 0x96, 0x4a, 0x1a, 0xb8,
	0xa1, 0xa9, 0xcb, 0xf4, 0x61, 0xcb, 0xf5, 0xa1, 0x20, 0x4d, 0xcb, 0x77, 0x4c, 0x27, 0xa7, 0x3a,
	0x6f, 0xaf, 0xd8, 0xbc, 0xc6, 0x8c, 0xbf, 0x84, 0xad, 0x83, 0x24, 0xa1, 0x22, 0xd7, 0x05, 0xbb,
	0xa7, 0xb0, 0x2a, 0x8d, 0x6f, 0xaa, 0x34, 0x90, 0x4d, 0x07, 0xe9, 0xee, 0xf8, 0xa3, 0x78, 0x07,
	0xb6, 0xdf, 0xf2, 0x49, 0xca, 0xb1, 0x7f, 0x7c, 0xf2, 0x1a, 0xc3, 0x83, 0x88, 0x7f, 0xaf, 0xc1,
	0x9a, 0x9f, 0x81, 0xad, 0x48, 0xa6, 0xef, 0x50, 0xfa, 0x6e, 0x79, 0xcf, 0xbe, 0x74, 0x91, 0xcb,
	0x59, 0xa5, 0xce, 0x33, 0xf1, 0x0b, 0x65, 0xfb, 0xe2, 0x0a, 0xf5, 0x9e, 0xe9, 0x80, 0xc8, 0x74,
	0x2a, 0xb8, 0xab, 0xb1, 0x41, 0x83, 0x4b, 0xfe, 0x0f, 0xcd, 0xa9, 0xc8, 0xb9, 0x3e, 0xcb, 0x44,
	0xca, 0xb5, 0x2d, 0xab, 0x41, 0xc1, 0x86, 0x8e, 0x4d, 0x24, 0xfe, 0x01, 0x60, 0xb6, 0x5e, 0x4d,
	0xf5, 0x79, 0xf1, 0x97, 0x36, 0xa6, 0x89, 0x8c, 0xd3, 0xc4, 0xf3, 0x30, 0x26, 0x79, 0x06, 0x9b,
	0x2c, 0x49, 0x52, 0x83, 0xcf, 0x26, 0x47, 0x69, 0xe2, 0xfe, 0x5f, 0x0d, 0xba, 0x10, 0x8d, 0x5f,
	0xc3, 0x8a, 0x6d, 0x88, 0x7d, 0xa5, 0xa8, 0xb4, 0x47, 0xb5, 0xb6, 0x61, 0x3c, 0x66, 0x1a, 0x2f,
	0xd9, 0x95, 0x87, 0x0e, 0x6e, 0x69, 0xca, 0x51, 0x79, 0xca, 0xfb, 0xff, 0xac, 0xc3, 0xc6, 0x81,
	0xf9, 0x3a, 0x18, 0xa2, 0xb4, 0x63, 0x3f, 0x82, 0xad, 0x05, 0xbd, 0x27, 0x4f, 0xdc, 0x1c, 0xaa,
	0x3f, 0x03, 0x3a, 0xbb, 0x3d, 0xf7, 0xfd, 0xd0, 0x0b, 0xdf, 0x0f, 0xbd, 0x43, 0xf3, 0xfd, 0x40,
	0x8e, 0x60, 0x73, 0x5e, 0x7f, 0xc9, 0xe3, 0xf0, 0x54, 0x2a, 0x54, 0xb9, 0xd3, 0x76, 0x87, 0x15,
	0x7a, 0x78, 0x04, 0x5b, 0x0b, 0x62, 0x1c, 0x18, 0x55, 0x6b, 0xf4, 0x52, 0x46, 0x07, 0xd0, 0x2c,
	0xa9, 0x28, 0xf1, 0x19, 0xaf, 0x0b, 0xeb, 0x0d, 0x5c, 0xfa, 0xd0, 0x9a, 0xd3, 0x3c, 0xd2, 0x29,
	0x33, 0x59, 0x80, 0x59, 0xc6, 0xe3, 0x5b, 0x68, 0x96, 0x84, 0x28, 0xf0, 0xb8, 0x2e, 0x73, 0x9d,
	0xff, 0x55, 0x9c, 0x78, 0x22, 0x07, 0x00, 0x5e, 0x3e, 0x92, 0x94, 0x17, 0x10, 0xd7, 0xf4, 0xaa,
	0x80, 0xa8, 0x90, 0x9a, 0x6f, 0x00, 0xdc, 0xf2, 0x4f, 0x44, 0xae, 0xc9, 0x23, 0xff, 0xd8, 0x16,
	0xa5, 0x26, 0x34, 0xa3, 0x42, 0x27, 0x66, 0x00, 0x28, 0xe5, 0x6d, 0x00, 0xbe, 0x06, 0x98, 0x89,
	0x4a, 0x00, 0xb8, 0x26, 0x33, 0x37, 0xcc, 0x73, 0xa3, 0xac, 0x24, 0xc4, 0xd7, 0x5a, 0xa1, 0x2e,
	0x4b, 0x21, 0xfa, 0xd0, 0x9a, 0x53, 0x85, 0x30, 0xcf, 0x2a, 0xa9, 0x58, 0x0a, 0x72, 0x08, 0x9b,
	0xf3, 0x4b, 0x3c, 0xfc, 0xd3, 0x2b, 0x57, 0xfb, 0x0d, 0x0f, 0x66, 0x6b, 0x61, 0x6d, 0x87, 0xff,
	0x79, 0xf5, 0x36, 0x5f, 0x0a, 0xf4, 0x12, 0xd6, 0xc3, 0x6a, 0x25, 0x3b, 0x0e, 0x61, 0x61, 0xd5,
	0xde, 0xd4, 0xd2, 0xf2, 0x76, 0x0d, 0x2d, 0xad, 0xd8, 0xb8, 0xcb, 0x20, 0xce, 0x57, 0xad, 0xff,
	0xc5, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x7d, 0xbd, 0xeb, 0x75, 0x0c, 0x00, 0x00,
}
